import Erdos593.TripleSystem.CanonicalAtomCanonicity
import Erdos593.TripleSystem.ConstructiblePositiveObligatory
import Erdos593.TripleSystem.ObligatoryClassification
import Erdos593.TripleSystem.SingleEdgePieceConstructible

/-!
# Minimal generators and one-point indecomposable obligatory systems

This module states the two corollaries of the canonical atom normal form.
`AtomGenerated` replaces arbitrary finite bipartite expansion generators by
one triple and expansions of finite two-vertex-connected bipartite cores.
`OnePointDecomposable` uses a literal isomorphism to a nontrivial one-point
amalgam; the edge-partition certificate is a proof-facing characterization,
not a weaker definition.
-/

namespace Erdos593

universe u

namespace TripleSystem
namespace CanonicalAtom

/-- A finite two-vertex-connected bipartite graph, packaged with the finite
vertex type needed by the canonical atom theorem. -/
structure TwoConnectedBipartiteCore where
  Vertex : Type u
  vertexFintype : Fintype Vertex
  graph : _root_.SimpleGraph Vertex
  twoVertexConnected :
    @CanonicalAtom.IsTwoVertexConnected Vertex vertexFintype graph
  bipartite : graph.Colorable 2

/-- The finite class generated by edgeless systems, one triple, and expansions
of finite two-vertex-connected bipartite graphs, under the two assembly
operations and isomorphism. -/
inductive AtomGenerated : {V E : Type u} → TripleSystem V E → Prop
  | ofEdgeless (V : Type u) [Fintype V] :
      AtomGenerated (edgeless V)
  | ofOneTriple :
      AtomGenerated (privateVertexExpansion oneEdgeGraph.{u})
  | ofCore (C : TwoConnectedBipartiteCore.{u}) :
      AtomGenerated (privateVertexExpansion C.graph)
  | disjointUnion {V E W D : Type u}
      {F : TripleSystem V E} {G : TripleSystem W D}
      (hF : AtomGenerated F) (hG : AtomGenerated G) :
      AtomGenerated (F.disjointUnion G)
  | amalgam {V₀ E₀ V₁ E₁ : Type u}
      {F₀ : TripleSystem V₀ E₀} {F₁ : TripleSystem V₁ E₁}
      (h₀ : AtomGenerated F₀) (h₁ : AtomGenerated F₁)
      (r₀ : V₀) (r₁ : V₁) :
      AtomGenerated (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁)
  | ofIso {V E V' E' : Type u}
      {F : TripleSystem V E} {F' : TripleSystem V' E'}
      (hF : AtomGenerated F) (f : TripleSystem.Iso F F') :
      AtomGenerated F'

/-- A literal nontrivial one-point-amalgam presentation. Both factors must
contain a hyperedge. No support-based surrogate is built into the definition. -/
def OnePointDecomposable {V E : Type u} (F : TripleSystem V E) : Prop :=
  ∃ (V₀ E₀ V₁ E₁ : Type u)
      (F₀ : TripleSystem V₀ E₀) (F₁ : TripleSystem V₁ E₁)
      (r₀ : V₀) (r₁ : V₁),
    Nonempty E₀ ∧ Nonempty E₁ ∧
      TripleSystem.Isomorphic F
        (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁)

/-- A system is one-point indecomposable when it has no literal nontrivial
one-point-amalgam presentation. -/
def OnePointIndecomposable {V E : Type u} (F : TripleSystem V E) : Prop :=
  ¬ OnePointDecomposable F

/-- An internal two-part edge certificate: both parts are nonempty, partition
all hyperedges, and their point supports meet in exactly one root. -/
structure EdgeOnePointDecomposition {V E : Type u}
    (F : TripleSystem V E) where
  left : Set E
  right : Set E
  left_nonempty : left.Nonempty
  right_nonempty : right.Nonempty
  disjoint : Disjoint left right
  total : left ∪ right = Set.univ
  root : V
  support_intersection :
    F.edgeSupportSet left ∩ F.edgeSupportSet right = {root}

/-- Every atom-generated system belongs to the original constructive class. -/
theorem AtomGenerated.constructible {V E : Type u} {F : TripleSystem V E}
    (hF : AtomGenerated F) : Constructible F := by
  induction hF with
  | ofEdgeless V => exact Constructible.ofEdgeless V
  | ofOneTriple =>
      exact Constructible.ofExpansion oneEdgeGraph.{u} oneEdgeGraph_colorable_two
  | ofCore C =>
      letI : Fintype C.Vertex := C.vertexFintype
      exact Constructible.ofExpansion C.graph C.bipartite
  | disjointUnion _ _ ihF ihG => exact Constructible.disjointUnion ihF ihG
  | amalgam _ _ r₀ r₁ ih₀ ih₁ => exact Constructible.amalgam ih₀ ih₁ r₀ r₁
  | ofIso _ f ih => exact Constructible.ofIso ih f

/-- Conversely, the canonical atom forest refines every original constructive
presentation to the smaller atom generator family. This includes explicit
restoration of isolated points by a finite edgeless factor. -/
theorem atomGenerated_of_constructible {V E : Type u}
    {F : TripleSystem V E} (hF : Constructible F) : AtomGenerated F := by
  classical
  have hfin := hF.finiteTypes
  letI : Finite V := hfin.1
  letI : Finite E := hfin.2
  letI : Fintype V := Fintype.ofFinite V
  letI : Fintype E := Fintype.ofFinite E
  letI : DecidableEq E := Classical.decEq E
  have hintr : F.isolatedReduction.Intrinsic :=
    (isObligatory_iff_isolatedReduction_intrinsic F).mp hF.isObligatory
  letI : Fintype F.NonIsolatedPoint := Fintype.ofFinite _
  letI : DecidableEq F.NonIsolatedPoint := Classical.decEq _
  letI : DecidableRel F.isolatedReduction.levi.Adj := Classical.decRel _
  -- The canonical atom forest generates the isolated reduction.
  have hK : AtomGenerated F.isolatedReduction := by
    set K := F.isolatedReduction with hKdef
    have hpieces : ∀ A : CanonicalAtom.Index K,
        AtomGenerated (K.edgeRestriction
          (CanonicalAtom.edges K hintr.1 hintr.2.1 A)) := by
      intro A
      cases A with
      | singleton e hzero =>
          rcases
            CanonicalAtom.atomRestriction_is_singleEdge_or_cycleBlockExpansion.{u, u, u}
              (V := F.NonIsolatedPoint) (E := E) K hintr.1 hintr.2.1
              (CanonicalAtom.Index.singleton e hzero) with ⟨hiso⟩
          exact AtomGenerated.ofIso
            (AtomGenerated.ofIso AtomGenerated.ofOneTriple
              (oneEdgeExpansionSingleEdgePieceIso K e)) hiso.symm
      | cycleBlock C hC B =>
          rcases
            CanonicalAtom.atomRestriction_is_singleEdge_or_cycleBlockExpansion.{u, u, u}
              (V := F.NonIsolatedPoint) (E := E) K hintr.1 hintr.2.1
              (CanonicalAtom.Index.cycleBlock C hC B) with ⟨hiso⟩
          have hcore : AtomGenerated
              (privateVertexExpansion (CanonicalAtom.cycleBlockCore K C B)) :=
            AtomGenerated.ofCore
              { Vertex := _
                vertexFintype := inferInstance
                graph := CanonicalAtom.cycleBlockCore K C B
                twoVertexConnected :=
                  CanonicalAtom.cycleBlockCore_isTwoVertexConnected K hintr.1
                    hintr.2.1 C hC B
                bipartite :=
                  CanonicalAtom.cycleBlockCore_isBipartite K hintr.1 hintr.2.1
                    hintr.2.2 C hC B }
          exact AtomGenerated.ofIso hcore hiso.symm
    have key : ∀ pieces : List (Set E), K.RunningEdgeAssembly pieces →
        (∀ S ∈ pieces, AtomGenerated (K.edgeRestriction S)) →
        AtomGenerated (K.edgeRestriction (edgePieceUnion pieces)) := by
      intro pieces
      induction pieces with
      | nil =>
          intro _ _
          letI : IsEmpty (K.EdgeSupport (∅ : Set E)) :=
            ⟨by rintro ⟨x, e, he, hxe⟩; exact he⟩
          letI : Fintype (K.EdgeSupport (∅ : Set E)) := Fintype.ofFinite _
          exact AtomGenerated.ofIso
            (AtomGenerated.ofEdgeless (K.EdgeSupport (∅ : Set E)))
            (edgelessIsoEdgeRestrictionEmpty K)
      | cons S pieces ih =>
          rintro ⟨hprev, -, hEdges, hSupports⟩ hgen
          have hPrev := ih hprev (fun T hT => hgen T (by simp [hT]))
          have hS := hgen S (by simp)
          rcases hSupports with hDisjoint | ⟨r, hRoot⟩
          · exact AtomGenerated.ofIso (AtomGenerated.disjointUnion hPrev hS)
              (K.edgeRestrictionUnionIsoDisjointUnion hEdges hDisjoint)
          · exact AtomGenerated.ofIso
              (AtomGenerated.amalgam hPrev hS (K.edgeSupportLeftRoot hRoot)
                (K.edgeSupportRightRoot hRoot))
              (K.edgeRestrictionUnionIsoOnePointAmalgamation hEdges hRoot)
    obtain ⟨assembly⟩ := CanonicalAtom.exists_atomRunningAssembly K hintr
    have hall := key (CanonicalAtom.atomEdgeSets K hintr.1 hintr.2.1 assembly.atoms)
      assembly.running (by
        intro S hS
        rw [CanonicalAtom.atomEdgeSets, List.mem_map] at hS
        obtain ⟨A, -, rfl⟩ := hS
        exact hpieces A)
    rw [assembly.total] at hall
    exact AtomGenerated.ofIso hall
      (K.edgeRestrictionUnivIso F.isolatedReduction_hasNoIsolatedPoints)
  -- Restore the finitely many isolated points as an edgeless factor.
  letI : Fintype {x : V // F.IsIsolated x} := Fintype.ofFinite _
  refine AtomGenerated.ofIso
    (AtomGenerated.disjointUnion hK
      (AtomGenerated.ofEdgeless {x : V // F.IsIsolated x})) ?_
  refine
    { vertexEquiv := (Equiv.sumComm _ _).trans (Equiv.sumCompl F.IsIsolated)
      edgeEquiv := Equiv.sumEmpty E EdgelessEdge.{u}
      map_inc_iff := ?_ }
  rintro (y | y) (e | d)
  · exact Iff.rfl
  · exact d.down.elim
  · exact iff_of_false id (fun h => y.2 e h)
  · exact d.down.elim

/-- The atom generators give exactly the previously classified constructive
class, not merely its isolated reduction. -/
theorem atomGenerated_iff_constructible {V E : Type u}
    (F : TripleSystem V E) :
    AtomGenerated F ↔ Constructible F :=
  ⟨AtomGenerated.constructible, atomGenerated_of_constructible⟩

/-- Manuscript-facing minimal-generator theorem for the finite obligatory
class, stated directly on the original system including isolated points. -/
theorem isObligatory_iff_atomGenerated {V E : Type u}
    (F : TripleSystem V E) [Fintype V] [Fintype E] :
    F.IsObligatory ↔ AtomGenerated F := by
  classical
  constructor
  · intro hobl
    have hred : Constructible F.isolatedReduction :=
      (isObligatory_iff_constructible_isolatedReduction F).mp hobl
    letI : Fintype {x : V // F.IsIsolated x} := Fintype.ofFinite _
    refine atomGenerated_of_constructible (Constructible.ofIso
      (Constructible.disjointUnion hred
        (Constructible.ofEdgeless {x : V // F.IsIsolated x})) ?_)
    refine
      { vertexEquiv := (Equiv.sumComm _ _).trans (Equiv.sumCompl F.IsIsolated)
        edgeEquiv := Equiv.sumEmpty E EdgelessEdge.{u}
        map_inc_iff := ?_ }
    rintro (y | y) (e | d)
    · exact Iff.rfl
    · exact d.down.elim
    · exact iff_of_false id (fun h => y.2 e h)
    · exact d.down.elim
  · intro hgen
    exact hgen.constructible.isObligatory

/-- For connected reduced finite systems, the literal amalgam definition is
equivalent to the exact two-part edge/support certificate. Connectedness is
essential here: without it an identified root need not support edges on both
sides. -/
theorem onePointDecomposable_iff_edgeOnePointDecomposition
    {V E : Type u} (F : TripleSystem V E)
    [Fintype V] [Fintype E]
    (hconnected : F.levi.Connected)
    (hreduced : F.HasNoIsolatedPoints) :
    OnePointDecomposable F ↔ Nonempty (EdgeOnePointDecomposition F) := by
  classical
  constructor
  · rintro ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, ⟨a⟩, ⟨b⟩, ⟨f⟩⟩
    set L : Set E := {e | ∃ c : E₀, f.edgeEquiv e = Sum.inl c} with hL
    set R : Set E := {e | ∃ c : E₁, f.edgeEquiv e = Sum.inr c} with hR
    set root : V :=
      f.vertexEquiv.symm (OnePointAmalgamation.left r₀ r₁ r₀) with hroot
    have hLne : L.Nonempty := ⟨f.edgeEquiv.symm (Sum.inl a), a, by simp⟩
    have hRne : R.Nonempty := ⟨f.edgeEquiv.symm (Sum.inr b), b, by simp⟩
    have hdisj : Disjoint L R := by
      rw [Set.disjoint_left]
      rintro e ⟨c, hc⟩ ⟨d, hd⟩
      rw [hc] at hd
      exact Sum.inl_ne_inr hd
    have htotal : L ∪ R = Set.univ := by
      ext e
      simp only [Set.mem_union, Set.mem_univ, iff_true, hL, hR, Set.mem_setOf_eq]
      cases hfe : f.edgeEquiv e with
      | inl c => exact Or.inl ⟨c, rfl⟩
      | inr c => exact Or.inr ⟨c, rfl⟩
    -- A point supported on both sides is the image of the amalgamation root.
    have hsub : ∀ x : V, x ∈ F.edgeSupportSet L → x ∈ F.edgeSupportSet R →
        x = root := by
      rintro x ⟨e, ⟨c, hce⟩, hxe⟩ ⟨e', ⟨d, hde⟩, hxe'⟩
      have h₀ : (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁).Inc
          (f.vertexEquiv x) (Sum.inl c) := by
        rw [← hce]
        exact (f.map_inc_iff x e).mp hxe
      have h₁ : (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁).Inc
          (f.vertexEquiv x) (Sum.inr d) := by
        rw [← hde]
        exact (f.map_inc_iff x e').mp hxe'
      obtain ⟨x₀, _, hx₀⟩ : f.vertexEquiv x ∈
        OnePointAmalgamation.left r₀ r₁ '' F₀.edgeSet c := h₀
      obtain ⟨y₁, _, hy₁⟩ : f.vertexEquiv x ∈
        OnePointAmalgamation.right r₀ r₁ '' F₁.edgeSet d := h₁
      have hcross :=
        (OnePointAmalgamation.left_eq_right_iff r₀ r₁ x₀ y₁).mp
          (hx₀.trans hy₁.symm)
      have hq : f.vertexEquiv x = OnePointAmalgamation.left r₀ r₁ r₀ := by
        rw [← hx₀, hcross.1]
      rw [hroot, ← hq, Equiv.symm_apply_apply]
    -- Connectedness of the Levi graph forces the two supports to meet.
    have hne : (F.edgeSupportSet L ∩ F.edgeSupportSet R).Nonempty := by
      obtain ⟨e₀, he₀⟩ := hLne
      obtain ⟨e₁, he₁⟩ := hRne
      by_contra hempty
      rw [Set.not_nonempty_iff_eq_empty] at hempty
      set X : Set (V ⊕ E) :=
        {z | Sum.elim (fun x => x ∈ F.edgeSupportSet L) (fun e => e ∈ L) z}
        with hX
      have hstep : ∀ z w : V ⊕ E, z ∈ X → F.levi.Adj z w → w ∈ X := by
        rintro (x | e) (y | g) hz hadj
        · exact absurd hadj F.not_levi_adj_point_point
        · have hxg : F.Inc x g := F.levi_adj_point_edge.mp hadj
          have hxL : x ∈ F.edgeSupportSet L := hz
          rcases (htotal ▸ Set.mem_univ g : g ∈ L ∪ R) with hgL | hgR
          · exact hgL
          · exact absurd (Set.eq_empty_iff_forall_notMem.mp hempty x
              ⟨hxL, ⟨g, hgR, hxg⟩⟩) (by simp)
        · exact ⟨e, hz, F.levi_adj_edge_point.mp hadj⟩
        · exact absurd hadj F.not_levi_adj_edge_edge
      have hwalk : ∀ (z w : V ⊕ E), F.levi.Walk z w → z ∈ X → w ∈ X := by
        intro z w p
        induction p with
        | nil => exact id
        | cons hadj _ ih => exact fun hz => ih (hstep _ _ hz hadj)
      obtain ⟨p⟩ := hconnected.preconnected (Sum.inr e₀) (Sum.inr e₁)
      have he₁L : e₁ ∈ L := hwalk _ _ p he₀
      have hncard : Set.ncard {x : V | F.Inc x e₁} ≠ 0 := by
        rw [F.edge_ncard e₁]
        decide
      obtain ⟨x, hx⟩ := Set.nonempty_of_ncard_ne_zero hncard
      exact absurd (Set.eq_empty_iff_forall_notMem.mp hempty x
        ⟨⟨e₁, he₁L, hx⟩, ⟨e₁, he₁, hx⟩⟩) (by simp)
    refine ⟨⟨L, R, hLne, hRne, hdisj, htotal, root, ?_⟩⟩
    obtain ⟨p, hp⟩ := hne
    have hpr : p = root := hsub p hp.1 hp.2
    subst hpr
    refine Set.Subset.antisymm (fun y hy => hsub y hy.1 hy.2) ?_
    rintro y hy
    rw [Set.mem_singleton_iff] at hy
    subst hy
    exact hp
  · rintro ⟨D⟩
    have hiso : Iso
        (OnePointAmalgamation.amalgam
          (F.edgeRestriction D.left) (F.edgeRestriction D.right)
          (F.edgeSupportLeftRoot D.support_intersection)
          (F.edgeSupportRightRoot D.support_intersection))
        (F.edgeRestriction (D.left ∪ D.right)) :=
      F.edgeRestrictionUnionIsoOnePointAmalgamation D.disjoint
        D.support_intersection
    rw [D.total] at hiso
    exact ⟨F.EdgeSupport D.left, D.left, F.EdgeSupport D.right, D.right,
      F.edgeRestriction D.left, F.edgeRestriction D.right, _, _,
      ⟨⟨D.left_nonempty.choose, D.left_nonempty.choose_spec⟩⟩,
      ⟨⟨D.right_nonempty.choose, D.right_nonempty.choose_spec⟩⟩,
      ⟨(hiso.trans (F.edgeRestrictionUnivIso hreduced)).symm⟩⟩

/-- The canonical one-triple system is one-point indecomposable. -/
theorem oneTriple_onePointIndecomposable :
    OnePointIndecomposable
      (privateVertexExpansion oneEdgeGraph.{u}) := by
  rintro ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, ⟨a⟩, ⟨b⟩, ⟨f⟩⟩
  have h : f.edgeEquiv.symm (Sum.inl a) = f.edgeEquiv.symm (Sum.inr b) := by
    rw [oneEdgeGraph_edge_eq (f.edgeEquiv.symm (Sum.inl a)),
      oneEdgeGraph_edge_eq (f.edgeEquiv.symm (Sum.inr b))]
  exact Sum.inl_ne_inr (f.edgeEquiv.symm.injective h)

/-- The expansion of a finite two-vertex-connected bipartite core is
one-point indecomposable. -/
theorem coreExpansion_onePointIndecomposable
    (C : TwoConnectedBipartiteCore.{u}) :
    OnePointIndecomposable (privateVertexExpansion C.graph) := by
  classical
  letI : Fintype C.Vertex := C.vertexFintype
  rintro ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, ⟨a⟩, ⟨b⟩, ⟨f⟩⟩
  set G := C.graph with hG
  set L : Set G.edgeSet := {e | ∃ c : E₀, f.edgeEquiv e = Sum.inl c} with hL
  set R : Set G.edgeSet := {e | ∃ c : E₁, f.edgeEquiv e = Sum.inr c} with hR
  have hLne : L.Nonempty := ⟨f.edgeEquiv.symm (Sum.inl a), a, by simp⟩
  have hRne : R.Nonempty := ⟨f.edgeEquiv.symm (Sum.inr b), b, by simp⟩
  have htotal : ∀ e : G.edgeSet, e ∈ L ∨ e ∈ R := by
    intro e
    cases hfe : f.edgeEquiv e with
    | inl c => exact Or.inl ⟨c, hfe⟩
    | inr c => exact Or.inr ⟨c, hfe⟩
  set Lcov : C.Vertex → Prop :=
    fun x => ∃ e ∈ L, x ∈ (e : Sym2 C.Vertex) with hLcov
  set Rcov : C.Vertex → Prop :=
    fun x => ∃ e ∈ R, x ∈ (e : Sym2 C.Vertex) with hRcov
  -- Core points covered by both sides are all the amalgamation root.
  have hboth : ∀ x y : C.Vertex, Lcov x → Rcov x → Lcov y → Rcov y → x = y := by
    intro x y hxL hxR hyL hyR
    have key : ∀ z : C.Vertex, Lcov z → Rcov z →
        f.vertexEquiv (PrivateVertexExpansion.core G z) =
          OnePointAmalgamation.left r₀ r₁ r₀ := by
      rintro z ⟨e, ⟨c, hce⟩, hze⟩ ⟨e', ⟨d, hde⟩, hze'⟩
      have h₀ : (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁).Inc
          (f.vertexEquiv (PrivateVertexExpansion.core G z)) (Sum.inl c) := by
        rw [← hce]
        exact (f.map_inc_iff _ e).mp hze
      have h₁ : (OnePointAmalgamation.amalgam F₀ F₁ r₀ r₁).Inc
          (f.vertexEquiv (PrivateVertexExpansion.core G z)) (Sum.inr d) := by
        rw [← hde]
        exact (f.map_inc_iff _ e').mp hze'
      obtain ⟨x₀, _, hx₀⟩ :
        f.vertexEquiv (PrivateVertexExpansion.core G z) ∈
          OnePointAmalgamation.left r₀ r₁ '' F₀.edgeSet c := h₀
      obtain ⟨y₁, _, hy₁⟩ :
        f.vertexEquiv (PrivateVertexExpansion.core G z) ∈
          OnePointAmalgamation.right r₀ r₁ '' F₁.edgeSet d := h₁
      have hcross :=
        (OnePointAmalgamation.left_eq_right_iff r₀ r₁ x₀ y₁).mp
          (hx₀.trans hy₁.symm)
      rw [← hx₀, hcross.1]
    have hcc : PrivateVertexExpansion.core G x = PrivateVertexExpansion.core G y :=
      f.vertexEquiv.injective ((key x hxL hxR).trans (key y hyL hyR).symm)
    exact Sum.inl.inj hcc
  have hcard : 3 ≤ Fintype.card C.Vertex := C.twoVertexConnected.1
  have hnonempty : Nonempty C.Vertex := Fintype.card_pos_iff.mp (by omega)
  obtain ⟨r, hr⟩ : ∃ r : C.Vertex, ∀ x, Lcov x → Rcov x → x = r := by
    by_cases hex : ∃ x, Lcov x ∧ Rcov x
    · obtain ⟨x₀, hx₀⟩ := hex
      exact ⟨x₀, fun x hxL hxR => hboth x x₀ hxL hxR hx₀.1 hx₀.2⟩
    · exact ⟨Classical.arbitrary C.Vertex, fun x hxL hxR => absurd ⟨x, hxL, hxR⟩ hex⟩
  have hother : ∀ e : G.edgeSet, ∃ w, w ∈ (e : Sym2 C.Vertex) ∧ w ≠ r := by
    rintro ⟨e, he⟩
    induction e using Sym2.inductionOn with
    | _ x y =>
        have hxy : x ≠ y := (show G.Adj x y from he).ne
        by_cases hx : x = r
        · refine ⟨y, by simp, ?_⟩
          rw [← hx]
          exact fun h => hxy h.symm
        · exact ⟨x, by simp, hx⟩
  obtain ⟨ea, heaL⟩ := hLne
  obtain ⟨eb, hebR⟩ := hRne
  obtain ⟨w₀, hw₀, hw₀r⟩ := hother ea
  obtain ⟨w₁, hw₁, hw₁r⟩ := hother eb
  -- Deleting the unique shared core point keeps the graph connected, but no
  -- edge of the induced graph can cross between the two sides.
  have hstep : ∀ z w : ↥{y : C.Vertex | y ≠ r},
      (G.induce {y : C.Vertex | y ≠ r}).Adj z w → Lcov z.1 → Lcov w.1 := by
    intro z w hadj hz
    have hadj' : G.Adj z.1 w.1 := hadj
    set e : G.edgeSet := ⟨s(z.1, w.1), hadj'⟩ with he
    have hze : z.1 ∈ (e : Sym2 C.Vertex) := by simp [he]
    have hwe : w.1 ∈ (e : Sym2 C.Vertex) := by simp [he]
    rcases htotal e with hmemL | hmemR
    · rw [hLcov]
      exact ⟨e, hmemL, hwe⟩
    · exact absurd (hr z.1 hz (by rw [hRcov]; exact ⟨e, hmemR, hze⟩)) z.2
  have hwalk : ∀ (z w : ↥{y : C.Vertex | y ≠ r})
      (_ : (G.induce {y : C.Vertex | y ≠ r}).Walk z w), Lcov z.1 → Lcov w.1 := by
    intro z w p
    induction p with
    | nil => exact id
    | cons hadj _ ih => exact fun hz => ih (hstep _ _ hadj hz)
  obtain ⟨p⟩ := (C.twoVertexConnected.2 r).preconnected ⟨w₀, hw₀r⟩ ⟨w₁, hw₁r⟩
  have hw₁L : Lcov w₁ :=
    hwalk ⟨w₀, hw₀r⟩ ⟨w₁, hw₁r⟩ p (by rw [hLcov]; exact ⟨ea, heaL, hw₀⟩)
  exact hw₁r (hr w₁ hw₁L (by rw [hRcov]; exact ⟨eb, hebR, hw₁⟩))

/-- Manuscript-facing classification of connected reduced obligatory systems
with at least one hyperedge. -/
theorem connected_reduced_obligatory_onePointIndecomposable_iff
    {V E : Type u} (F : TripleSystem V E)
    [Fintype V] [Fintype E]
    (hconnected : F.levi.Connected)
    (hreduced : F.HasNoIsolatedPoints)
    (hobligatory : F.IsObligatory)
    (hnonempty : Nonempty E) :
    OnePointIndecomposable F ↔
      TripleSystem.Isomorphic F
          (privateVertexExpansion oneEdgeGraph.{u}) ∨
        ∃ C : TwoConnectedBipartiteCore.{u},
          TripleSystem.Isomorphic F (privateVertexExpansion C.graph) := by
  classical
  constructor
  · intro hindec
    letI : DecidableEq V := Classical.decEq V
    letI : DecidableEq E := Classical.decEq E
    letI : DecidableRel F.levi.Adj := Classical.decRel _
    have hisoRed : Iso F.isolatedReduction F :=
      { vertexEquiv :=
          { toFun := Subtype.val
            invFun := fun x => ⟨x, hreduced x⟩
            left_inv := fun _ => Subtype.ext rfl
            right_inv := fun _ => rfl }
        edgeEquiv := Equiv.refl E
        map_inc_iff := fun _ _ => Iff.rfl }
    have hintr : F.Intrinsic :=
      (Iso.intrinsic_iff hisoRed).mp
        ((isObligatory_iff_isolatedReduction_intrinsic F).mp hobligatory)
    -- A single canonical atom carrying every hyperedge gives the two cases of
    -- the canonical atom type dichotomy.
    have hfinal : ∀ A : CanonicalAtom.Index F,
        TripleSystem.Isomorphic F
            (CanonicalAtom.atomRestriction F hintr.1 hintr.2.1 A) →
        TripleSystem.Isomorphic F (privateVertexExpansion oneEdgeGraph.{u}) ∨
          ∃ C : TwoConnectedBipartiteCore.{u},
            TripleSystem.Isomorphic F (privateVertexExpansion C.graph) := by
      intro A hisoA
      cases A with
      | singleton e' hzero =>
          left
          rcases
            CanonicalAtom.atomRestriction_is_singleEdge_or_cycleBlockExpansion.{u, u, u}
              (V := V) (E := E) F hintr.1 hintr.2.1
              (CanonicalAtom.Index.singleton e' hzero) with ⟨hiso⟩
          exact (hisoA.trans ⟨hiso⟩).trans
            ⟨(oneEdgeExpansionSingleEdgePieceIso F e').symm⟩
      | cycleBlock C hC B =>
          right
          rcases
            CanonicalAtom.atomRestriction_is_singleEdge_or_cycleBlockExpansion.{u, u, u}
              (V := V) (E := E) F hintr.1 hintr.2.1
              (CanonicalAtom.Index.cycleBlock C hC B) with ⟨hiso⟩
          exact ⟨{ Vertex := _
                   vertexFintype := inferInstance
                   graph := CanonicalAtom.cycleBlockCore F C B
                   twoVertexConnected :=
                     CanonicalAtom.cycleBlockCore_isTwoVertexConnected F hintr.1
                       hintr.2.1 C hC B
                   bipartite :=
                     CanonicalAtom.cycleBlockCore_isBipartite F hintr.1 hintr.2.1
                       hintr.2.2 C hC B },
            hisoA.trans ⟨hiso⟩⟩
    obtain ⟨assembly⟩ := CanonicalAtom.exists_atomRunningAssembly F hintr
    obtain ⟨e⟩ := hnonempty
    have hmem : e ∈ edgePieceUnion
        (CanonicalAtom.atomEdgeSets F hintr.1 hintr.2.1 assembly.atoms) := by
      rw [assembly.total]
      trivial
    have hnil : assembly.atoms ≠ [] := by
      intro h
      rw [h] at hmem
      simp [CanonicalAtom.atomEdgeSets, edgePieceUnion] at hmem
    obtain ⟨A, rest, hatoms⟩ := List.exists_cons_of_ne_nil hnil
    have hrun := assembly.running
    have htot := assembly.total
    rw [hatoms, CanonicalAtom.atomEdgeSets, List.map_cons] at hrun htot
    obtain ⟨-, -, hEdges, hSupports⟩ := hrun
    refine hfinal A ?_
    set Sprev : Set E :=
      edgePieceUnion (List.map (CanonicalAtom.edges F hintr.1 hintr.2.1) rest)
      with hSprev
    have htot' : Sprev ∪ CanonicalAtom.edges F hintr.1 hintr.2.1 A = Set.univ :=
      htot
    have hSAne : (CanonicalAtom.edges F hintr.1 hintr.2.1 A).Nonempty := by
      obtain ⟨e', he'⟩ := CanonicalAtom.atomOf_surjective F hintr.1 hintr.2.1 A
      exact ⟨e', he'⟩
    -- Indecomposability forces the earlier atoms to carry no hyperedge.
    have hprevEmpty : Sprev = ∅ := by
      rcases Set.eq_empty_or_nonempty Sprev with hempty | hne
      · exact hempty
      · exfalso
        apply hindec
        apply (onePointDecomposable_iff_edgeOnePointDecomposition F hconnected
          hreduced).mpr
        have hroot : ∃ r : V,
            F.edgeSupportSet Sprev ∩
                F.edgeSupportSet (CanonicalAtom.edges F hintr.1 hintr.2.1 A) =
              {r} := by
          rcases hSupports with hdisj | ⟨r, hr⟩
          · exfalso
            obtain ⟨e₀, he₀⟩ := hne
            obtain ⟨e₁, he₁⟩ := hSAne
            have hinter : F.edgeSupportSet Sprev ∩
                F.edgeSupportSet (CanonicalAtom.edges F hintr.1 hintr.2.1 A) =
                  ∅ :=
              Set.disjoint_iff_inter_eq_empty.mp hdisj
            set X : Set (V ⊕ E) :=
              {z | Sum.elim (fun x => x ∈ F.edgeSupportSet Sprev)
                (fun f => f ∈ Sprev) z} with hX
            have hstep : ∀ z w : V ⊕ E, z ∈ X → F.levi.Adj z w → w ∈ X := by
              rintro (x | f) (y | g) hz hadj
              · exact absurd hadj F.not_levi_adj_point_point
              · have hxg : F.Inc x g := F.levi_adj_point_edge.mp hadj
                have hxL : x ∈ F.edgeSupportSet Sprev := hz
                rcases (htot' ▸ Set.mem_univ g :
                    g ∈ Sprev ∪ CanonicalAtom.edges F hintr.1 hintr.2.1 A) with
                  hgL | hgR
                · exact hgL
                · exact absurd (Set.eq_empty_iff_forall_notMem.mp hinter x
                    ⟨hxL, ⟨g, hgR, hxg⟩⟩) (by simp)
              · exact ⟨f, hz, F.levi_adj_edge_point.mp hadj⟩
              · exact absurd hadj F.not_levi_adj_edge_edge
            have hwalk : ∀ (z w : V ⊕ E), F.levi.Walk z w → z ∈ X → w ∈ X := by
              intro z w p
              induction p with
              | nil => exact id
              | cons hadj _ ih => exact fun hz => ih (hstep _ _ hz hadj)
            obtain ⟨p⟩ := hconnected.preconnected (Sum.inr e₀) (Sum.inr e₁)
            have he₁L : e₁ ∈ Sprev := hwalk _ _ p he₀
            have hncard : Set.ncard {x : V | F.Inc x e₁} ≠ 0 := by
              rw [F.edge_ncard e₁]
              decide
            obtain ⟨x, hx⟩ := Set.nonempty_of_ncard_ne_zero hncard
            exact absurd (Set.eq_empty_iff_forall_notMem.mp hinter x
              ⟨⟨e₁, he₁L, hx⟩, ⟨e₁, he₁, hx⟩⟩) (by simp)
          · exact ⟨r, hr⟩
        obtain ⟨r, hr⟩ := hroot
        exact ⟨⟨Sprev, CanonicalAtom.edges F hintr.1 hintr.2.1 A, hne, hSAne,
          hEdges, htot', r, hr⟩⟩
    rw [hprevEmpty, Set.empty_union] at htot'
    show TripleSystem.Isomorphic F
      (F.edgeRestriction (CanonicalAtom.edges F hintr.1 hintr.2.1 A))
    rw [htot']
    exact ⟨(F.edgeRestrictionUnivIso hreduced).symm⟩
  · rintro (hone | ⟨C, hC⟩) hdec
    · obtain ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, h₀, h₁, hiso⟩ := hdec
      exact oneTriple_onePointIndecomposable
        ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, h₀, h₁, hone.symm.trans hiso⟩
    · obtain ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, h₀, h₁, hiso⟩ := hdec
      exact coreExpansion_onePointIndecomposable C
        ⟨V₀, E₀, V₁, E₁, F₀, F₁, r₀, r₁, h₀, h₁, hC.symm.trans hiso⟩

end CanonicalAtom
end TripleSystem
end Erdos593
